# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atria < Formula
  desc "Agent multiplexer for your terminal"
  homepage "https://github.com/sethdeckard/atria"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sethdeckard/atria/releases/download/v0.3.2/atria_0.3.2_darwin_amd64.tar.gz"
      sha256 "f9f7f7ced33d82cfeac66ffde3275ead30141ffbf6a1fdd2747545a7d0b71d77"

      define_method(:install) do
        bin.install "atria"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sethdeckard/atria/releases/download/v0.3.2/atria_0.3.2_darwin_arm64.tar.gz"
      sha256 "85969262c80f36ab76e00a31f56f7f8d2cbb52400edf62e1810a866ca65a23f1"

      define_method(:install) do
        bin.install "atria"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethdeckard/atria/releases/download/v0.3.2/atria_0.3.2_linux_amd64.tar.gz"
      sha256 "aa6eddd8b2b6f91f28c87a6bf331315423e132d2bf186381e92253f0be58e7ad"
      define_method(:install) do
        bin.install "atria"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethdeckard/atria/releases/download/v0.3.2/atria_0.3.2_linux_arm64.tar.gz"
      sha256 "2c516b91c3cadf26efb90836bac3e88ec866b55c20678c8601a1e022bd77bc46"
      define_method(:install) do
        bin.install "atria"
      end
    end
  end
end
