# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loadout < Formula
  desc "Skill manager for Claude and Codex"
  homepage "https://github.com/sethdeckard/loadout"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sethdeckard/loadout/releases/download/v0.5.0/loadout_0.5.0_darwin_amd64.tar.gz"
      sha256 "eda0f4248f3b9cefaae856550fe710a738911953dc7706867860b18508c19050"

      define_method(:install) do
        bin.install "loadout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sethdeckard/loadout/releases/download/v0.5.0/loadout_0.5.0_darwin_arm64.tar.gz"
      sha256 "a18fb602abed51c1cf683c5c5708d16228fc411d0a77622ce4e3b80f73c2edbb"

      define_method(:install) do
        bin.install "loadout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethdeckard/loadout/releases/download/v0.5.0/loadout_0.5.0_linux_amd64.tar.gz"
      sha256 "5cc5ef132280eb0f7fa47952187ca64e13f61780354acfb39ed6ce8fbb7f6c88"
      define_method(:install) do
        bin.install "loadout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethdeckard/loadout/releases/download/v0.5.0/loadout_0.5.0_linux_arm64.tar.gz"
      sha256 "61fdd8a5bba697cbd0b33259df754d867e28f21ffb7a41c01c196e78b40ff8b2"
      define_method(:install) do
        bin.install "loadout"
      end
    end
  end
end
