# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "3b94dabb7264e9bd5951544ac3185e25c5b3ea679deb7e9097b8eccddf29487d"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7ef53637966b1eb84e01a3665c75deb8e668fcfa5264b6bd91d3de5050e02df3"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1cb5a9a0627ef5da964ea954e867b2289cc6730a24aca48f477f9039afc861e"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "668ccbd84d87c4e3ee01a94e64193b5cf4063529af9bcf7e4f416160541f28d6"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atlas"
  desc "Smart, automatic map of every Git repo under your projects root"
  homepage "https://github.com/sethdeckard/atlas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
  end

  # No zap stanza required
end
