# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "da0325aa7e397bd6c33d9093e87006fa8a7a5929d55636f3298eb6f5758bcea1"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa40323d743aef62b58939a0a5fe750cc3b463ec572711012e9f3ced7e2064aa"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cb60956d308820d0877431d479a6d761f9d6bc5f2c3761ff1dfdaf3270e1272b"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "96496b96322bb42b827fc3080bfe2ec727b2fc489aba8ea7b8d19da2ef97dd8c"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atlas"
  desc "Smart, automatic map of every Git repo under your projects root"
  homepage "https://github.com/sethdeckard/atlas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
  end

  # No zap stanza required
end
