# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "d064acc2ecf55d9f7ad5ccfd32382a3021866e9b9d02d5b9919eeeeb5f39bb0b"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28b9b88f31a0b526e4bd3fc7b3baac740465b827a299d99a7bfa833ad098186e"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "993e0aa19c149f74c9166d08d0ca7f4c47c0b058b5c0f48ce6d0bdcb9ab81db8"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e8afab92a113c4b10c0bb651294a411f3fcc5d7fc653e2d393ed1ec4481ba96"
      url "https://github.com/sethdeckard/atlas/releases/download/v#{version}/atlas_#{version}_linux_arm64.tar.gz"
    end
  end

  name "atlas"
  desc "Smart, automatic map of every Git repo under your projects root"
  homepage "https://github.com/sethdeckard/atlas"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
  end

  # No zap stanza required

end
