# This file was generated by GoReleaser. DO NOT EDIT.
cask "atria" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "46d8cf440b81e5baf137aba7c1b9ec14e6e92f3e8a25105b472dfe655eb7d68a"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f97007f4d87a64860b915a1cfbf996208c54fbeb6af7987797b27137289e3871"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2c71529224acc72ae87dc0026308f42ab71b321917a0f82fb009053c70055876"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0903f65bafde9c06e9095b460858953913c9bbea1047cb0eb3196cad9b493214"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atria"
  desc "Agent multiplexer for your terminal"
  homepage "https://github.com/sethdeckard/atria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atria"]
    end
  end

  # No zap stanza required
end
