# This file was generated by GoReleaser. DO NOT EDIT.
cask "atria" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "42b9b6bfcba2f644a6e1971095c22915ea56fd0096b09da3113e9884e8499503"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "69612e27658b941638c69a8859f9c2e49a969707868b890be05d8392dc6c58e6"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "99faede376561257e61db548839f0133acdcafd72f9031fa9cf300ea97781a73"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc8e4f2c73b075b1e724a56862254b5ecfbfa2142c6421f0a109ef7876cf7760"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atria"
  desc "Agent multiplexer for your terminal"
  homepage "https://github.com/sethdeckard/atria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atria"]
    end
  end

  # No zap stanza required
end
