# This file was generated by GoReleaser. DO NOT EDIT.
cask "atria" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "27e53694fbf2c60d148c17eb38b116668481c62e1a49fffa6ef27fde6e308486"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2864354f622d7dc9aaeb7799195a227bd20d0b246d5e1134f4eda3cd3b31e5ae"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "43494ab62fbb6b28a5b747f01a4a70d17e89779fd309639d41aa73961567a87d"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f12eb309b262e772d92eaea7aa5eecfce0693ed90f796d7cf740960b297aac6"
      url "https://github.com/sethdeckard/atria/releases/download/v#{version}/atria_#{version}_linux_amd64.tar.gz"
    end
  end

  name "atria"
  desc "Agent multiplexer for your terminal"
  homepage "https://github.com/sethdeckard/atria"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atria"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atria"]
    end
  end

  # No zap stanza required
end
