# This file was generated by GoReleaser. DO NOT EDIT.
cask "loadout" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "bab1e3bb9e6af4bbb7fcae8d70c991041c50261b91d013e83723a5b001eded4b"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "588ed2106a0e18153dc152aea486703dac709de7331b35e38897bf5088f05711"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "95ac12ddf7539d98994ed38b77ee2b3f1f055b2767394158b274dc37800eade6"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "121c694a5df2d33a4f93d405edc997b6504ab9db835922c8c26fee03adc3e19d"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_linux_amd64.tar.gz"
    end
  end

  name "loadout"
  desc "Skill manager for Claude and Codex"
  homepage "https://github.com/sethdeckard/loadout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loadout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loadout"]
    end
  end

  # No zap stanza required
end
