# This file was generated by GoReleaser. DO NOT EDIT.
cask "loadout" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "d602bb552967b49fc98b057de1fb9fe9dee299d6f4f32686a937928324f49b5f"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b58a4aaebdf5c758d3f10df10a0157ddfb4e61763d67b307fb9f25c8b8a0fa2"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4cf58341734beab7b40bbf00edf3931aee42c504b7672c4b9c203cc340a6536d"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad1bb703b5bcbe682e8ecf1e99177a649bf17d2fe240bcc15cf69e47526335fc"
      url "https://github.com/sethdeckard/loadout/releases/download/v#{version}/loadout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loadout"
  desc "Skill manager for Claude and Codex"
  homepage "https://github.com/sethdeckard/loadout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loadout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loadout"]
    end
  end

  # No zap stanza required

end
